### ISSUE TITLE
platformio.ini  missing default for tlora-v2-1-1.6 board

### ISSUE THREAD

**Issue by costonisp** [meshtastic/Meshtastic-device#1114]
While trying to compile for TTGO  T3 V1.6.1  I had some difficulties when I choose 
default_envs = tlora-v2

So added  default_envs = tlora-v2-1-1.6  as line 20 in platformio.ini

**Comment by thebentern** [comment]
That board is actually the tlora v2-1-1.6. TTGO's labeling is unfortunately particularly misleading on that board. I have a few of them. 

Also on the the default_envs, those are only a convenience to uncomment so that you don't need to specify the target every time. You can instead just run `platformio run --environment tlora-v2-1-1.6 --target upload --upload-port yourcomport`.
You can also run this from the VSCode extension if you have that:
![image](https://user-images.githubusercontent.com/9000580/150236895-68570c93-f145-4dfd-9c39-463e6f6432ce.png)

**Comment by costonisp** [comment]
tnx for your explanation.
I am a atom/platformio beginner and it took me some time to find out I had to use tlora-v2-1-1.6 as default, otherwise a added user_button does not work.
If it had been at the top in platformio.ini I would have uncommented it right away, but there was no entry for this board.

So my suggestion to add it as line 20 in platformio.ini . That makes it eaysier for beginners without digging in the source code to find this board.

I have more 'difficulties' with this board, the voltege measurement is inaccurate but I opened a topic for this in the forum.

**Comment by thebentern** [comment]
Added default_env. Closing

**Comment by thebentern** [comment]
@costonisp if you're confident in that ADC change for battery level, would you mind putting in a pull request with those changes?
This is the file that contains the config for that particular board now (this changed very recently):
![image](https://user-images.githubusercontent.com/9000580/150359519-422c0175-10ab-4a5e-ac11-966dc083ef06.png)
