### ISSUE TITLE
1.3 [Bug] New Routing with two units delivers message but sometimes the ACK returned is Max Retransmission Reached

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1610]
Seems to only happen when there are only two devices on the network.

In the image below all of the messages were received by the other device and shows on the device screen

![IMG_2472](https://user-images.githubusercontent.com/1795163/183458152-fdf5d83a-3e39-404f-9792-8d5765ac2755.PNG)

**Comment by GUVWAF** [comment]
This might not be a bug, but something that may happen in an RF environment. If the implicit ACK somehow does not end up at the sender, it will do a retransmission. However, then the other node will not send an implicit ACK again, because it already did. I see in the source that only packets with want_ack will ACK a resent packet. 
The reason why you only see this with two nodes in the network could be that then another node’s implicit ACK will end up at the sender.

**Comment by GUVWAF** [comment]
feh123 reported this on Discord as well. 
We could actually let nodes re-ACK a retransmission for broadcast messages as well, but we should be careful that we are not ACK-ing a rebroadcast again, as this would overload the channel. Right now, the receiving node will likely log “_Ignoring incoming msg, because we've already seen it_” when it receives the retransmission. This is good behavior for _rebroadcasts_, but maybe not for _retransmissions_. In order to re-ACK a retransmission, we could check whether the hop_limit is still at maximum, so we know it is the original sender that is retransmitting. 
I would like to know whether this is the desired behavior, then I could try to implement and test this.

**Comment by garthvh** [comment]
Seems especially pronounced in the same room while testing, I have not been able to replicate this very well with more distance between the nodes.

**Comment by garthvh** [comment]
> 

This sounds right to me.
