### ISSUE TITLE
t-beam v0.7 power indicate bug

### ISSUE THREAD

**Issue by cronyx** [meshtastic/Meshtastic-device#620]
hello, I have a t-beam v0.7 and they do not show the battery status, the indicator always shows charging.
![photo_2021-01-02_12-21-35](https://user-images.githubusercontent.com/2557102/103454433-16506c80-4cf5-11eb-8cec-e3180d3c4715.jpg)

**Comment by mc-hamster** [comment]
I may have exposed this bug when fixing #535.

My guess is powerStatus->getHasBattery() is not detecting that the t-beam v0.7 has a battery.

**Comment by mc-hamster** [comment]
getHasBattery returns a bool which is set by a class that is inherited from the AXP20X library. That should probably also check the value of the voltage divider in the event the AXP is not present.

There's a lot of inheritance going on here, not something I'd feel comfortable fixing without an v0.7 on hand.

**Comment by mc-hamster** [comment]
@cronyx Could you take a picture of the screen that shows the battery percentage and include the log file on this ticket? I think I see how to fix this problem without working in the classes.

**Comment by cronyx** [comment]
![photo_2021-01-03_11-06-33](https://user-images.githubusercontent.com/2557102/103474360-1fecd980-4db4-11eb-87ad-b61164a3d211.jpg)

**Comment by mc-hamster** [comment]
Alright. I think I have an idea of how to fix this.

thank you

**Comment by thebentern** [comment]
I think this is the same behavior I'm noticing on the TLora32 T3_V1.6 boards. They always display as if powered. Because of that I believe, they never appear to enter any form of sleep mode, draining my 18650s very quickly.
![image](https://user-images.githubusercontent.com/9000580/106630100-23a18680-6541-11eb-8382-add78b42b638.png)

**Comment by mc-hamster** [comment]
> I think this is the same behavior I'm noticing on the TLora32 T3_V1.6 boards. They always display as if powered. Because of that I believe, they never appear to enter any form of sleep mode, draining my 18650s very quickly.
> ![image](https://user-images.githubusercontent.com/9000580/106630100-23a18680-6541-11eb-8382-add78b42b638.png)

It very well could be the same. Both the 0.7 and your board don't have a power management chip.

**Comment by thebentern** [comment]
> It very well could be the same. Both the 0.7 and your board don't have a power management chip.
I'm guessing this one of the reasons the latest iteration of the T-Beams is the preferred hardware. I had hoped to make some very lean usage solar powered relays with these TLora32s, but it seems I may have picked the wrong board for the job. The choice was made in an attempt to save a few bucks and since I didn't have a use for the GPS, given that these would be repeater nodes.

**Comment by mc-hamster** [comment]
I think you have picked a good board, but there's a bug somewhere in how we go into a lower power mode.

**Comment by thebentern** [comment]
Possibly related to #330 ?

**Comment by geeksville** [comment]
yeah - I bet my recent checkin to fix the the voltage sensing fixes this bug.  @thebentern can you see if >=1.1.46 fixes things for you.

**Comment by thebentern** [comment]
@geeksville , Thanks! I think we're getting reasonable values now, based on what I'm seeing in the display. 
![image](https://user-images.githubusercontent.com/9000580/107879138-bbd23080-6e9c-11eb-983d-c65e9b7d6664.png)

I'm a little bit confused though, because my board in router / low power mode still doesn't go into light sleep cycle on battery power (and disconnected from BT). I thought that was controlled by **wait_bluetooth_secs**, but maybe I'm misunderstanding the power state transitions? Any ideas?

```
meshtastic --info
Connected to radio
my_node_num: 2442571748
num_channels: 13
region: "1.0-US"
hw_model: "tlora-v2-1-1.6"
firmware_version: "1.1.46"
packet_id_bits: 32
current_packet_id: 1235425311
node_num_bits: 32
message_timeout_msec: 300000
min_app_version: 20120

preferences {
  wait_bluetooth_secs: 60
  screen_on_secs: 60
  phone_sds_timeout_sec: 4294967295
  mesh_sds_timeout_secs: 4294967295
  ls_secs: 86400
  min_wake_secs: 10
  region: US
  gps_operation: GpsOpMobile
  gps_update_interval: 86400
  gps_attempt_time: 300
  is_router: true
  is_low_power: true
}

```

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/cheep-solar-light-build-progress/2493/8

**Comment by sachaw** [comment]
Dis this get resolved?

**Comment by thebentern** [comment]
@sachaw it is for my TLoRA v2 1.6 boards and for every board with this type of issue, setting an `adc_multiplier_override` is an option
