### ISSUE TITLE
Position Broadcast Change Parameter

### ISSUE THREAD

**Issue by lmatte7** [meshtastic/Meshtastic-device#845]
I asked this [here](https://meshtastic.discourse.group/t/position-broadcast-question/3694) in the forums as well. 

I noticed in the [docs](https://meshtastic.org/docs/software/settings/gps#position_broadcast_secs) for `position_broadcast_secs` is mentions this:

```
How often our position is sent to the mesh (but only if it has changed significantly).
```

Would it be possible to make this an adjustable value?

**Comment by srichs** [comment]
This is an option that is included with the protobuf definitions in the radioconfig.proto file. You could set this using the Python CLI by calling:

``` Shell
meshtastic  --port /dev/ttyUSB0 --set position_broadcast_secs 1
```

If you were writing code for some other language you could access this value through the Protocol Buffers generated for the given language. You could also get the value by using the --get option:

``` Shell
meshtastic  --port /dev/ttyUSB0 --get position_broadcast_secs
```

**Comment by lmatte7** [comment]
Thanks for the response! I was able to change that successfully, but I noticed in testing that it sends the same GPS coordinates unless there’s a large change in the position of the radio. I was wondering if there’s a way to change how often _new_ GPS coordinates are sent with location updates

**Comment by srichs** [comment]
Oh yeah, that makes sense, the position_broadcast_secs field is mainly related to the PositionPlugin which handles how the position is sent. 

You probably would want to change the gps_update_interval which is also under the radioconfig protobuf. Ensure that the gps_operation value is the default or GpsOpMobile so that the device will make use of the gps_update_interval value. The default value for gps_update_interval is 30 seconds. You could also change the gps_attempt_time which is a value for how long the GPS should try to get an updated position each time it reaches the update interval. Fine tuning those should get you a more desirable output.

**Comment by garthvh** [comment]
The new smart position broadcast should fix this issue.

**Comment by mc-hamster** [comment]
Closing. Answers are in the comment.
