### ISSUE TITLE
Setting owner via remote admin changes brightness

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [meshtastic/Meshtastic-device#887]
When changing owner names via remote administration, the brightness of the screen constantly sweeps as thought you were pressing down the brightness key. It will keep doing it until the update has finished.

Hardware: Heltech WiFi LoRa 32 v2
Firmware: Heltech v2.0 1.2.45

**Comment by garthvh** [comment]
This also happens when a Heltec or TTGO Lora32 is connected to my Mac mini with meshwatch running.

**Comment by thebentern** [comment]
This happens with the LoRA32 v1 on any meshtastic poo python command recently. I'm not sure which release version this behavior started on but we need to prioritize fixing it.

**Comment by garthvh** [comment]
This behavior is not present in 1.50

**Comment by thebentern** [comment]
The issue in my case was solved at least partly in Meshtastic-python due to a windows specific bug with pyserial I believe. I can't  repro it. Closing this for now. @KrazyKerbalnaut please check to see that the latest firmware (1.2.50) resolves your issue, and if it does not, we'll open a new issue with the details.
